# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  softbody_config = debug

else ifeq ($(config),release)
  softbody_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := softbody

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

softbody:
ifneq (,$(softbody_config))
	@echo "==== Building softbody ($(softbody_config)) ===="
	@${MAKE} --no-print-directory -C . -f softbody.make config=$(softbody_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f softbody.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   softbody"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"