# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  moss_config = debug
  hexagon_config = debug

else ifeq ($(config),release)
  moss_config = release
  hexagon_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := moss hexagon

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

moss:
ifneq (,$(moss_config))
	@echo "==== Building moss ($(moss_config)) ===="
	@${MAKE} --no-print-directory -C . -f moss.make config=$(moss_config)
endif

hexagon: moss
ifneq (,$(hexagon_config))
	@echo "==== Building hexagon ($(hexagon_config)) ===="
	@${MAKE} --no-print-directory -C . -f hexagon.make config=$(hexagon_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f moss.make clean
	@${MAKE} --no-print-directory -C . -f hexagon.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   moss"
	@echo "   hexagon"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"